_target_: slot_diffusion_policy.model.slot.autoencoder.SlotAutoencoder
encoder:
  _target_: slot_diffusion_policy.model.slot.encoder.encoder_resnet18
slot_attention:
  _target_: slot_diffusion_policy.model.slot.slot_attention.SlotAttention
  in_features: 512
  num_iterations: 3
  num_slots: 5
  slot_size: 64
  mlp_hidden_size: 128
  learnable_slots: True
decoder:
  _target_: slot_diffusion_policy.model.slot.decoder.decoder
  num_slots: 5