_target_: slot_diffusion_policy.model.slot_autoencoder.SlotAutoencoder
encoder:
  _target_: slot_diffusion_policy.model.slot_autoencoder.encoder
slot_attention:
  _target_: slot_diffusion_policy.model.slot_autoencoder.SlotAttention
  in_features: 64
  num_iterations: 3
  num_slots: 5
  slot_size: 64
  mlp_hidden_size: 128
decoder:
  _target_: slot_diffusion_policy.model.slot_autoencoder.decoder